protected/models/Post.php
<?php

/**
 * This is the model class for table "post".
 *
 * The followings are the available columns in table 'post':
 * @property integer $postid
 * @property string $title
 * @property string $content
 * @property integer $addTime
 * @property integer $upTime
 * @property integer $userId
 * @property integer $courseId
 *
 * The followings are the available model relations:
 * @property Tcomment[] $tcomments
 * @property User $user
 * @property Course $course
 */
class Post extends EntityActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Post the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	public function behaviors(){
		return array(
			'commentable'=>array('class'=>'CommentableBehavior'),
			'voteable'=>array('class'=>'VoteableBehavior'),
			//'voteable'=>array('class'=>'application.components.behaviors.FollowableBehavior'),
			'followable'=>array('class'=>'FollowableBehavior'),
			'postHelper'=>array('class'=>'PostHelperBehavior'),
		    'softDeleteActiveRecordBehavior' => array(
                                'class' => 'SoftDeleteBehavior',
             ),		
		);
	}
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{post}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('userId,title,content,groupId','required'),
			array('upTime, addTime, userId, commentNum, voteUpNum, voteDownNum,isTop, isDigest, postableEntityId', 'numerical', 'integerOnly'=>true),
			array('content','filter','filter'=>array($obj=new CHtmlPurifier(),'purify')),			
			array('title', 'length', 'max'=>255),
			array('id, title, content, upTime, addTime, userId, commentNum, voteUpNum,voteDownNum, isTop, isDigest, postableEntityId', 'safe', 'on'=>'search'),	
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'postableEntity'=> array(self::BELONGS_TO, 'Entity', 'postableEntityId'),
//			'comments' => array(self::HAS_MANY, 'Comment', 'postid',
//					'order'=>'addTime DESC'),
			'user' => array(self::BELONGS_TO, 'UserInfo', 'userId'),
			'author' => array(self::BELONGS_TO, 'UserInfo', 'userId'),
			'course' => array(self::BELONGS_TO, 'Course', 'courseId'),	
			'group' => array(self::BELONGS_TO, 'Group', 'groupId'),	
		            // 通过Post.entityId 取得 最新的一条Comment数据
//			'commentCount' => array(self::STAT, 'Comment', 'postid'),
//			'votedownCount'=>array(self::STAT,'Vote','postid','condition'=>"value<=0"),
//			'voteupCount'=>array(self::STAT,'Vote','postid','condition'=>"value>0"),
//			'voteUpers'=>array(self::MANY_MANY,'UserInfo','vote(entityId,userId)','condition'=>"value>0"),
			
		);
	}

	public  function getLastComment(){
		$criteria = new CDbCriteria();
		$criteria->condition = "t.commentableEntityId=".$this->entityId;
		$criteria->order = "addTime desc";
		$result = Comment::model()->find($criteria);
		return $result;
	}
	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'postid' => 'Postid',
			'title' => Yii::t('app','标题'),
			'content' => Yii::t('app','内容'),
			'addTime' => Yii::t('app','创建时间'),
			'upTime' => Yii::t('app','更新时间'),
			'userId' => 'Userid',
			'courseId' => 'Courseid',
		);
	}


	/**
	 * comment事件
	 * Enter description here ...
	 * @param unknown_type $event
	 */		
/*	public function onCommentAdded($event){
		$this->raiseEvent("onCommentAdded",$event);
	}
*/	

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('postid',$this->postid);
		$criteria->compare('title',$this->title,true);
		$criteria->compare('content',$this->content,true);
		$criteria->compare('addTime',$this->addTime);
		$criteria->compare('upTime',$this->upTime);
		$criteria->compare('userId',$this->userId);
		$criteria->compare('courseId',$this->courseId);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
/*
	public function updateVoteCount(){
		$sql = "select count(voteid) as num from post p left join post_comment c on p.postid=c.postid left join post_comment_vote v on v.commentid=c.commentid where p.postid=".$this->postid;
		$count = Yii::app()->db->createCommand($sql)->queryRow();
		$this->count_vote = $count['num'] + $this->voteupCount + $this->votedownCount;
		$this->save();

	}*/
	
	public function getPageUrl(){
		return Yii::app()->createUrl('/group/post/view',array('id'=>$this->id));
	}
}

protected/controllers/PostController.php
<?php

class PostController extends AbleController
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column1';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		//	'postOnly + delete', // we only allow deletion via POST request
		//'rights',
		);
	}
	public function allowedActions()
	{
		return 'index, view';
	}

	public function actions() {
		return array(
		'toggleFollow'=>array(
					'class'=>'application.components.actions.ToggleFollowAction',),
		'addComment'=>array(
					'class'=>'application.components.actions.commentable.AddCommentAction',
		),
		'toggleVote'=>array(
					'class'=>'application.components.actions.ToggleVoteAction',
		));
	}
	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
		array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view','counter'),
		//'actions'=>array('view'),
				'users'=>array('*'),
		),
		array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update','toggleFollow','addComment','comment','toggleVote'),
				'users'=>array('@'),
		),
		array('deny',  // deny all users
				'users'=>array('*'),
		),
		);
	}





	public function actionUpdate($id){
		$model=$this->loadModel($id);
		if(Yii::app()->user->checkAccess('updatePost',array('post'=>$model))){
			// Uncomment the following line if AJAX validation is needed
			// $this->performAjaxValidation($model);

			if(isset($_POST['Post']))
			{
				$model->attributes=$_POST['Post'];
				if($model->save()){
					Yii::app()->user->setFlash('success',Yii::t('app','更新成功!'));
					$this->redirect(array('view','id'=>$model->id));
				}
			}

			$this->render('update',array(
			'model'=>$model,
			));
		}
	}

	/**
	 * 添加vote
	 * @param unknown_type $id
	 */
	/*	public function actionToggleVote($id,$value){

	$post = $this->loadModel($id);
	$post->toggleVote(Yii::app()->user->id,$value);
	$this->renderPartial('/vote/result',array('score'=>$post->voteUpNum,'voteUpers'=>$post->getVoteUperDataProvider()->getData()));

	}
	*/
	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
		$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 * modified by lsy 20130808
	 */
	public function actionIndex($groupid)
	{
		$dataProvider=new CActiveDataProvider('Post', array(
				'criteria'=>array(
						'condition'=>'groupid='.$groupid,
						'order'=>'addTime DESC',
		),
				'pagination'=>array(
						'pageSize'=>10,
		),
		));
		$group = Group::model()->findByPk($groupid);
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
			'group'=>$group,
		));
	}
	/*
	 * modified by lsy 20130808
	 */
	/**
	 * 被要求显示一条comment
	 * @param unknown_type $id
	 */
	public function actionComment($id){
		$comment = Comment::model()->findByPk($id);
		$post = $comment->commentableEntity->getModel();
		$this->redirect(array('group/post','id'=>$post->id));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Post the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Post::model()->findByPk($id);
		if($model===null)
		throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Post $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='post-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/post/_comment.php
<div class="dxd-post-comment-item" data-commentId="<?php echo $data->id;?>">
<hr/>
<table style="width:100%">
	<tr>
	<!--
		<td style="width:40px;vertical-align:top;padding-top:24px;padding-left:10px;">
					<?php echo CHtml::ajaxLink(' ',array('vote/postcomment','commentId'=>$data->id,'value'=>1),array('success'=>'js:function(data){var item=$(".dxd-post-comment-item[data-commentId='.$data->id.']"); item.find(".dxd-post-comment-up").addClass("dxd-voted");item.find(".dxd-post-comment-vote-result").html(data);}'),array('class'=>'dxd-post-comment-up '.($data->voteUpNum ? "dxd-voted" : "")));?>
					<?php // echo CHtml::ajaxLink(' ',array('vote/postcomment','commentId'=>$data->id,'value'=>0),array('success'=>'js:function(data){var item =$(".dxd-post-comment-item[data-commentId='.$data->id.']");item.find(".dxd-post-comment-vote-result").html(data);}'),array('class'=>'dxd-post-comment-down '.($data->voteUpNum ? "dxd-voted" : "")));?>
		</td>
	-->
		<td style="width:60px;vertical-align:top;">
		<?php $img = CHtml::image(Yii::app()->baseUrl."/".DxdUtil::xImage($data->user->face, 50, 50),"images",array('style'=>'width:50px;height:50px;'));
				echo CHtml::link($img,$data->user->name,array('class'=>' dxd-username','data-userId'=>$data->user->id));
		?>
		</td>
		<td>
			<div style="margin-bottom:5px;"><?php echo CHtml::link($data->user->name,$data->user->pageUrl,array('class'=>'dxd-username','data-userId'=>$data->user->id));?><span class="muted">&nbsp;&nbsp;<?php echo date("Y-m-d H:i",$data->addTime);?></span>
			<?php echo CHtml::ajaxLink(' ',array('comment/toggleVote','id'=>$data->id,'value'=>1),array('success'=>'js:function(data){var item=$(".dxd-post-comment-item[data-commentId='.$data->id.']"); item.find(".dxd-post-comment-up").addClass("dxd-voted");item.find(".dxd-post-comment-vote-result").html(data);}'),array('class'=>'pull-right dxd-post-comment-up '.($data->voteUpNum ? "dxd-voted" : "")));?>

			<div class="muted dxd-post-comment-vote-result pull-right" style="font-size:0.8em;padding-right:5px;" commentId="<?php echo $data->id?>"><?php if($data->voteUpNum || $data->voteDownNum) $this->renderPartial('//vote/result',array('score'=>$data->voteUpNum-$data->voteDownNum,'voteUpers'=>$data->getVoteUperDataProvider()->getData()));?></div>
			<div class="clearfix"></div>
			</div>
			<div class="dxd-post-comment-content" style="margin-bottom:30px;">
				<?php if($data->referId){?>
					<div class="dxd-post-comment-refer"><?php echo $data->refer->user->name;?>:<?php $output=strip_tags($data->refer->content);echo mb_strlen($output)>160 ? mb_substr($output,0,160,'utf8')."...":$output;?></div>
					<span style="font-weight:bold;color:#000;"><?php echo Yii::t('app','回复');?></span><?php echo CHtml::link($data->refer->user->name.":","#",array('style'=>'font-weight:bold;color:#000;'));?>
				<?php }?>
			<?php echo $data->content;?>
			</div>
			<div style="text-align:right" class="muted">
				<?php echo CHtml::link(Yii::t('app','回复'),'javascript:;',array('class'=>'muted','data-toggle'=>'collapse','data-target'=>'#dxd-comment-form'.$index));?>
				<?php // echo CHtml::link('删除','#',array('class'=>'muted'));?>
			</div>
			<div id="dxd-comment-form<?php echo $index;?>" class="collapse">
			<?php /** @var BootActiveForm $form */
			$form = $this->beginWidget('CActiveForm',array('action'=>array('post/addComment','id'=>$post->id))); ?>
			<?php echo $form->hiddenField($data,'referId',array('value'=>$data->id));?>
			<?php //echo $form->hiddenField($data,'id',array('value'=>$data->id));?>
			<div>
			<?php echo $form->textarea($data,'content',array('style'=>'width:96%;height:5em;margin:5px;','value'=>""));?>
			</div>
			<div>
			<?php $this->widget('booster.widgets.TbButton', array(
			    'context'=>'success',
			    'label'=>Yii::t('app','回复'),
			    'buttonType'=>'submit',
				'htmlOptions'=>array('class'=>'pull-right','style'=>'margin-right:15px;')
			    )); ?>
			</div>
			<?php $this->endWidget(); ?>
			</div>
		</td>
	</tr>
</table>
</div>

protected/views/post/_form.php
<?php
/* @var $this PostController */
/* @var $model Post */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'post-form',
	'enableAjaxValidation'=>isset($ajax)?true:false,
	'enableClientValidation'=>false,
	'clientOptions'=>array('validateOnSubmit'=>true,),
)); ?>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'title'); ?>
		<?php echo $form->textField($model,'title',array('class'=>'input-block-level')); ?>
		<?php echo $form->error($model,'title'); ?>
	</div>

	<div class="row">
	<?php  $this->widget('ext.kindeditor.KindEditor',
                    array(
                        'model'=>$model,
                        'attribute'=>'content',
                        )
                    ); ?>
		<?php echo $form->labelEx($model,'content'); ?>
		<?php echo $form->textArea($model,'content',array('style'=>'height:200px;width:100%;','class'=>'dxd-kind-editor')); ?>
		<?php
/*		$this->widget('ext.redactor.ERedactorWidget',array(
					'model'=>$model,
					'attribute'=>'content',
					'htmlOptions'=>array('id'=>'redactor_content'),
					// Redactor options
					'options'=>array(
							'lang'=>'zh_cn',
							'minHeight'=>200, // pixels
					        'fileUpload'=>Yii::app()->createUrl('post/fileUpload',array(
					            'attr'=>'content'
					        )),
					        'fileUploadErrorCallback'=>new CJavaScriptExpression(
					            'function(obj,json) { alert(json.error); }'
					        ),
					        'imageUpload'=>Yii::app()->createUrl('post/imageUpload',array(
					            'attr'=>'content'
					        )),
					        'imageGetJson'=>Yii::app()->createUrl('post/imageList',array(
					            'attr'=>'content'
					        )),
					        'imageUploadErrorCallback'=>new CJavaScriptExpression(
					            'function(obj,json) { alert(json.error); }'
					        ),
					),
			));*/

		?>
		<?php echo $form->error($model,'content'); ?>

	</div>
<br/>
	<div class="row buttons">
			<?php $this->widget('booster.widgets.TbButton', array(
    'context'=>'primary',
    'label'=>$model->isNewRecord ? Yii::t('app','发布') : Yii::t('app','保存'),
    'buttonType'=>'submit',
	'htmlOptions'=>array('class'=>'pull-right')
    )); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/post/_post.php
<?php foreach($posts as $post): ?>
<div class="posts" id="c<?php echo $post->id; ?>">

	<div class="author">
		<?php echo $post->userId; ?> says:
	</div>

	<div class="time">
		<?php echo date('F j, Y \a\t h:i a',$post->create_time); ?>
	</div>

	<div class="title">
	<?php echo CHtml::link(CHtml::encode($post->title), $post->getUrl()); ?>
		
	</div>

</div><!-- comment -->
<?php endforeach; ?>

protected/views/post/_post_item.php
<?php
?>
<div class="pull-left" style="width:100%">
<?php echo CHtml::link($data->title,array('post/view','id'=>$data->id),array('style'=>'font-size:1.2em;font-weight:bold;display:block;padding: 3px 0;'));?>
	<div class="muted">
	<div class="pull-left">by&nbsp;
		
<?php echo CHtml::link($data->user->name,$data->user->pageUrl,array('class'=>'muted dxd-username','data-userId'=>$data->user->id));?>
	<span>&nbsp;&nbsp;<?php echo Yii::t('app','最近回应：'?><?php echo date('Y-m-d H:i',$data->upTime);?></span>
	</div>
<div class="pull-right"><span class="dxd-post-info-item"><span class="dxd-bold"><?php echo $data->commentCount;?></span><?php echo Yii::t('app','回复'?></span><span class="dxd-post-info-item"><span class="dxd-bold"><?php echo $data->viewNum;?></span><?php echo Yii::t('app','浏览');?></span></div>	
	</div>
</div>
<!--  
<table class="pull-right dxd-post-info"  align="center">
<tr style="font-weight: bold;"><td>1</td><td>4</td><td>100</td></tr>
<tr class="muted" style="font-size:0.9em"><td>回复</td><td>顶</td><td>浏览</td></tr>
</table>
-->

<div class="clearfix"></div>

protected/views/post/_search.php
<?php
/* @var $this PostController */
/* @var $model Post */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'title'); ?>
		<?php echo $form->textField($model,'title',array('size'=>60,'maxlength'=>128)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'content'); ?>
		<?php echo $form->textArea($model,'content',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'create_time'); ?>
		<?php echo $form->textField($model,'create_time'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'update_time'); ?>
		<?php echo $form->textField($model,'update_time'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'userId'); ?>
		<?php echo $form->textField($model,'userId'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'courseId'); ?>
		<?php echo $form->textField($model,'courseId'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/post/_view.php
		<h3 ><?php echo $post->title;?></h3>
		<hr style="margin: 10px 0 20px 0"/>
		<table style="width:100%">
			<tr>
				<td style="width:60px;vertical-align:top;">
									<?php $img = CHtml::image(Yii::app()->baseUrl."/".DxdUtil::xImage($post->user->face, 50, 50),"images",array('style'=>'width:50px;height:50px;'));
						echo CHtml::link($img,$post->user->name,array('class'=>' dxd-username','data-userId'=>$post->user->id));
					?>
							<?php //echo CHtml::ajaxLink(' ',array('vote/post','id'=>$post->id,'value'=>1),array('success'=>'js:function(data){$(".dxd-post-up").addClass("dxd-voted");$(".dxd-post-vote-result").html(data);}'),array('class'=>'dxd-post-up '.($post->voteUpNum ? "dxd-voted" : "")));?>
							<?php //echo CHtml::ajaxLink(' ',array('vote/post','id'=>$post->id,'value'=>0),array('success'=>'js:function(data){$(".dxd-post-vote-result").html(data);}'),array('class'=>'dxd-post-down '));?>
				</td>
				<td>
					<?php echo CHtml::ajaxLink(' ',array('post/toggleVote','id'=>$post->id,'value'=>1),array('success'=>'js:function(data){$(".dxd-post-up").addClass("dxd-voted");$(".dxd-post-vote-result").html(data);}'),array('class'=>'pull-right dxd-post-up '.($post->voteUpNum ? "dxd-voted" : "")));?>

					<div style="margin-bottom:5px;"><?php echo CHtml::link($post->user->name,$post->user->pageUrl,array('class'=>'dxd-username','data-userId'=>$post->user->id));?><span class="muted">&nbsp;&nbsp;<?php echo date("Y-m-d H:i",$post->addTime);?></span>
					<?php //$img = CHtml::image(Yii::app()->baseUrl."/".DxdUtil::xImage($post->user->face, 25, 25),"images",array('style'=>'width:25px;height:25px;'));
						//echo CHtml::link($img,$post->user->name,array('class'=>'pull-right dxd-username','data-userId'=>$post->user->id));
					?>
					<div class="muted dxd-post-vote-result pull-right" style="font-size:0.8em;padding-right:5px;"><?php if($post->voteUpNum || $post->voteDownNum) $this->renderPartial('//vote/result',array('score'=>$post->voteUpNum-$post->voteDownNum,'voteUpers'=>$post->getVoteUperDataProvider()->getData()));?></div>
					<div class="clearfix"></div>
					</div>
					<div class="dxd-post-content" style="margin-bottom:30px;">
						<?php echo $post->content;?>
					</div>
					<?php  $this->widget('ext.jiathis.JiaThis');?>
				<?php if(Yii::app()->user->checkAccess('postAuthor',array('post'=>$post))):?>
					<div style="text-align:right" class="muted">
						<?php echo CHtml::link(Yii::t('app','编辑'),array('post/update','id'=>$post->id),array('class'=>'muted'));?>&nbsp;|&nbsp;
						<?php echo CHtml::link(Yii::t('app','删除'),array('post/delete','id'=>$post->id),array('class'=>'muted'));?>
					</div>
				<?php endif;?>
				</td>
			</tr>
		</table>
		<div>

		</div>

		<div>

		<?php
/* @var $this PostController */
/* @var $model Post */
/* @var $form CActiveForm */
?>


	<div style="margin-top:50px;">
	<?php
	$this->widget('booster.widgets.TbListView', array(
	'dataProvider'=>$post->getCommentDataProvider(array('pagination'=>array('pageSize'=>40))),
	'itemView'=>'/post/_comment',
	'viewData'=>array('post'=>$post),
	'summaryText'=>Yii::t('app','{count} 回复',array('{count}'=>$count)),
	'emptyText'=>false,
)); ?>
	</div>
<div >
<?php $comment = new Comment;?>
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'post-comment-form',
	'action'=>array('post/addComment','id'=>$post->id),
//	'enableAjaxValidation'=>isset($ajax)?true:false,
//	'enableClientValidation'=>true,
	'clientOptions'=>array('validateOnSubmit'=>true,),
)); ?>

	<?php echo $form->errorSummary($comment); ?>
	<?php if(!Yii::app()->user->isGuest){?>
	<div class="row" >
	<div style="margin-left:40px;">
		<h4><?php echo Yii::t('app','我的回复：'?></h4>

		<?php echo $form->textArea($comment,'content',array('rows'=>7,'style'=>'width:100%','class'=>'dxd-kind-editor')); ?>

		<?php echo $form->error($comment,'content'); ?>
		</div>
	</div>
<br/>
	<div class="row" style="maring-top:60px;">
			<?php $this->widget('booster.widgets.TbButton', array(
    'context'=>'success',
    'label'=>$comment->isNewRecord ? Yii::t('app','发布') : Yii::t('app','保存'),
    'buttonType'=>'submit',
	'htmlOptions'=>array('class'=>'pull-right')
    )); ?>
	</div>
<?php }else{
Yii::app()->user->returnUrl=Yii::app()->request->getUrl();;

	?>
	<div class="row" >
	<div style="margin-left:30px;">
	<h4><?php echo Yii::t('app','我的回复：')?></h4>
		<p><?php echo Yii::t('app','回复前请先'?><?php echo CHtml::link(Yii::t('app',' 登录 '),array('u/login'))?><?php echo Yii::t('app','或')?><?php echo CHtml::link(Yii::t('app',' 注册 '),array('u/register'));?></p>
	</div>
	</div>
<?php }?>
<?php $this->endWidget(); ?>

</div><!-- form -->


		</div>

protected/views/post/admin.php
<?php
/* @var $this PostController */
/* @var $model Post */

$this->breadcrumbs=array(
	'Posts'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Post', 'url'=>array('index')),
	array('label'=>'Create Post', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#post-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Posts</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'post-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'id',
		'title',
		'content',
		'create_time',
		'update_time',
		'userId',
		/*
		'courseId',
		*/
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

protected/views/post/update.php
<?php
/* @var $this PostController */
/* @var $model Post */
?>

<h3><?php echo Yii::t('app','编辑帖子')?></h3>
<div class="row dxd-course-body">
	<div class="col-sm-9 dxd-left-col">
	<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>
	</div>
	<div class="col-sm-3">
	</div>
</div>